build:
    environment:
        php:
            version: '7.2'
    tests:
        override:
            -
                command: vendor/bin/simple-phpunit -c phpunit.coverage.xml.dist
                coverage:
                    file: var/coverage/coverage.xml
                    format: clover

checks:
    php: true

filter:
    excluded_paths:
        - tests/*
